pipeline {
    agent any

    environment {
        EC2_USER = "ubuntu"
        EC2_HOST = "18.209.19.161"
        PEM_KEY = "home/ubuntu/access_key/key_pair.pem"
        APP_NAME = "flask-app"
        REMOTE_PATH = "/home/ubuntu/$APP_NAME"
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/Avihay1997/Project-Final'
            }
        }

        stage('Build & Test Flask App') {
            steps {
                sh 'pip install -r App/requirements.txt'
                sh 'python3 -m unittest' // Add test cases
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t flask-app -f App/Dockerfile .'
            }
        }

        stage('Deploy to EC2') {
            steps {
                sh """
                scp -i $PEM_KEY Docker/Dockerfile.yml ubuntu@$EC2_HOST:$REMOTE_PATH/
                ssh -i $PEM_KEY ubuntu@$EC2_HOST << EOF
                cd $REMOTE_PATH
                Dockerfile up -d --build
                EOF
                """
            }
        }
    }
}
