version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
      target: jenkins
    container_name: jenkins-server
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: always
    environment:
      - JAVA_OPTS=""

  flask:
    build:
      context: .
      dockerfile: Dockerfile
      target: flask
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    restart: always

volumes:
  jenkins_home:
