FROM python:3.11-slim

WORKDIR /App

COPY requirements.txt /App/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . /App/
RUN chmod +x /App/entrypoint.sh

EXPOSE 5000
ENTRYPOINT ["python3", "/App/app.py"]

CMD ["python3", "/App/app.py"]
