# Jenkins - First stage
FROM jenkins/jenkins:lts-jdk17 AS jenkins

USER root

RUN apt-get update && apt-get install -y \
    lsb-release \
    curl \
    gnupg \
    git \
    unzip \
    && rm -rf /var/lib/apt/lists/*

VOLUME ["/var/jenkins_home"]

EXPOSE 8080 50000

ENV JAVA_OPTS="-Xmx2g -Xms512m"

CMD ["java", "-jar", "/usr/share/jenkins/jenkins.war"]
